# Step 1: Build
FROM node:16-alpine as builder

WORKDIR /app

COPY backend/package.json backend/package-lock.json ./
RUN npm install

COPY backend ./
RUN npm run build

# Step 2: Execution
FROM node:16-alpine

WORKDIR /app

COPY --from=builder /app ./

EXPOSE 4000

CMD ["npm", "run", "start:dev"]
