# Etapa 1: Build da aplicação
FROM node:16-alpine as builder

WORKDIR /app

COPY backend/package.json backend/package-lock.json ./
RUN npm install

COPY backend ./
RUN npx prisma generate
RUN npx prisma migrate deploy

# Etapa 2: Execução da aplicação
FROM node:16-alpine

WORKDIR /app

COPY --from=builder /app ./

EXPOSE 4000

CMD ["npm", "run", "start:dev"]
